# Generated by Django 5.2.17 on 2026-08-12 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PRODUCTOS', 'Productos'), ('INVENTARIO', 'Inventario'), ('PRECIOS', 'Precios'), ('VENTAS', 'Ventas'), ('COMPLETA', 'Completa')], max_length=30)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('EXITOSA', 'Exitosa'), ('ERROR', 'Error'), ('PARCIAL', 'Parcial')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('registros_procesados', models.PositiveIntegerField(default=0)),
                ('registros_exitosos', models.PositiveIntegerField(default=0)),
                ('registros_error', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'sincronización',
                'verbose_name_plural': 'sincronizaciones',
                'db_table': 'sincronizaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SistemaIntegracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('POS', 'POS'), ('ERP', 'ERP'), ('CONTABLE', 'Contable'), ('MARKETPLACE', 'Marketplace'), ('OTRO', 'Otro')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sistema de integración',
                'verbose_name_plural': 'sistemas de integración',
                'db_table': 'sistemas_integracion',
            },
        ),
        migrations.CreateModel(
            name='ErrorIntegracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_error', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sincronizacion', models.ForeignKey(db_column='sincronizacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='integraciones.sincronizacion')),
            ],
            options={
                'verbose_name': 'error de integración',
                'verbose_name_plural': 'errores de integración',
                'db_table': 'errores_integracion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sincronizacion',
            name='sistema',
            field=models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.CASCADE, related_name='sincronizaciones', to='integraciones.sistemaintegracion'),
        ),
        migrations.CreateModel(
            name='IntegracionProducto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_externo', models.CharField(max_length=100)),
                ('codigo_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='integraciones', to='catalogo.producto')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.CASCADE, related_name='productos_integrados', to='integraciones.sistemaintegracion')),
            ],
            options={
                'verbose_name': 'integración de producto',
                'verbose_name_plural': 'integraciones de productos',
                'db_table': 'integracion_productos',
                'constraints': [models.UniqueConstraint(fields=('producto', 'sistema'), name='uq_integracion_producto_sistema')],
            },
        ),
        migrations.CreateModel(
            name='VentaExterna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('documento_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_externas', to='ventas.pedido')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_externas', to='integraciones.sistemaintegracion')),
            ],
            options={
                'verbose_name': 'venta externa',
                'verbose_name_plural': 'ventas externas',
                'db_table': 'ventas_externas',
                'constraints': [models.UniqueConstraint(fields=('pedido', 'sistema'), name='uq_venta_externa_pedido_sistema')],
            },
        ),
    ]
