# Generated by Django 5.2.17 on 2026-08-22 02:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoExternoEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('etag', models.CharField(blank=True, default='', max_length=255)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estado de recurso externo',
                'verbose_name_plural': 'estados de recursos externos',
                'db_table': 'recursos_externos_estado',
            },
        ),
        migrations.AlterField(
            model_name='sincronizacion',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTOS', 'Productos'), ('INVENTARIO', 'Inventario'), ('PRECIOS', 'Precios'), ('VENTAS', 'Ventas'), ('COMPLETA', 'Completa'), ('IMAGENES', 'Imágenes')], max_length=30),
        ),
        migrations.CreateModel(
            name='ImagenMatchPendiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruta_remota', models.CharField(max_length=500, unique=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('carpeta_marca', models.CharField(blank=True, default='', max_length=255)),
                ('url_origen', models.TextField(blank=True, default='')),
                ('nombre_normalizado', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('candidatos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('AUTO', 'Asignado automático')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, db_column='producto_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_imagen', to='catalogo.producto')),
                ('producto_imagen', models.ForeignKey(blank=True, db_column='producto_imagen_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_origen', to='catalogo.productoimagen')),
            ],
            options={
                'verbose_name': 'match de imagen pendiente',
                'verbose_name_plural': 'matches de imagen pendientes',
                'db_table': 'imagen_matches_pendientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
