# Generated by Django 5.2.17 on 2026-08-12 16:28

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sucursal',
                'verbose_name_plural': 'sucursales',
                'db_table': 'sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('VENTA', 'Venta'), ('AJUSTE', 'Ajuste'), ('TRASLADO', 'Traslado'), ('DEVOLUCION', 'Devolución')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('stock_anterior', models.DecimalField(decimal_places=3, max_digits=16)),
                ('stock_nuevo', models.DecimalField(decimal_places=3, max_digits=16)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_fisico', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('stock_reservado', models.DecimalField(decimal_places=3, default=0, max_digits=16)),
                ('stock_disponible', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('stock_fisico'), '-', models.F('stock_reservado')), output_field=models.DecimalField(decimal_places=3, max_digits=16))),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='catalogo.producto')),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
                'db_table': 'inventario',
                'constraints': [models.UniqueConstraint(fields=('producto', 'sucursal'), name='uq_inventario_producto_sucursal')],
            },
        ),
    ]
