# Generated by Django 5.2.17 on 2026-08-12 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_dato', models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('BOOLEANO', 'Booleano'), ('FECHA', 'Fecha')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'atributo',
                'verbose_name_plural': 'atributos',
                'db_table': 'atributos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'presentación',
                'verbose_name_plural': 'presentaciones',
                'db_table': 'presentaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('correo', models.EmailField(blank=True, default='', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSanitario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_registro', models.CharField(choices=[('INVIMA', 'INVIMA'), ('ICA', 'ICA'), ('OTRO', 'Otro')], max_length=30)),
                ('entidad', models.CharField(max_length=50)),
                ('numero_registro', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDO', 'Vencido'), ('SUSPENDIDO', 'Suspendido')], default='VIGENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'registro sanitario',
                'verbose_name_plural': 'registros sanitarios',
                'db_table': 'registros_sanitarios',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'unidad de medida',
                'verbose_name_plural': 'unidades de medida',
                'db_table': 'unidades_medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('nivel', models.SmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(db_index=True, max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('referencia_fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_producto', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('OTC', 'OTC'), ('DISPOSITIVO', 'Dispositivo'), ('COSMETICO', 'Cosmético'), ('OTRO', 'Otro')], max_length=30)),
                ('inventariable', models.BooleanField(default=True)),
                ('requiere_formula', models.BooleanField(default=False)),
                ('controlado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria')),
                ('marca', models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.marca')),
                ('presentacion', models.ForeignKey(blank=True, db_column='presentacion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.presentacion')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.proveedor')),
                ('registro_sanitario', models.ForeignKey(blank=True, db_column='registro_sanitario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.registrosanitario')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.TextField()),
                ('es_principal', models.BooleanField(default=False)),
                ('orden', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'imagen de producto',
                'verbose_name_plural': 'imágenes de producto',
                'db_table': 'producto_imagenes',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='presentacion',
            name='unidad_medida',
            field=models.ForeignKey(db_column='unidad_medida_id', on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones', to='catalogo.unidadmedida'),
        ),
        migrations.CreateModel(
            name='ProductoAtributo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(db_column='atributo_id', on_delete=django.db.models.deletion.CASCADE, related_name='producto_atributos', to='catalogo.atributo')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='producto_atributos', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'atributo de producto',
                'verbose_name_plural': 'atributos de producto',
                'db_table': 'producto_atributos',
                'constraints': [models.UniqueConstraint(fields=('producto', 'atributo'), name='uq_producto_atributo')],
            },
        ),
        migrations.CreateModel(
            name='ProductoEquivalente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='equivalentes', to='catalogo.producto')),
                ('producto_equivalente', models.ForeignKey(db_column='producto_equivalente_id', on_delete=django.db.models.deletion.CASCADE, related_name='equivalente_desde', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'producto equivalente',
                'verbose_name_plural': 'productos equivalentes',
                'db_table': 'productos_equivalentes',
                'constraints': [models.UniqueConstraint(fields=('producto', 'producto_equivalente'), name='uq_producto_equivalente')],
            },
        ),
        migrations.CreateModel(
            name='ProductoRelacionado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CROSS_SELL', 'Cross-sell'), ('UPSELL', 'Upsell'), ('ACCESORIO', 'Accesorio'), ('OTRO', 'Otro')], max_length=30)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='catalogo.producto')),
                ('producto_relacionado', models.ForeignKey(db_column='producto_relacionado_id', on_delete=django.db.models.deletion.CASCADE, related_name='relacionado_desde', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'producto relacionado',
                'verbose_name_plural': 'productos relacionados',
                'db_table': 'productos_relacionados',
                'constraints': [models.UniqueConstraint(fields=('producto', 'producto_relacionado', 'tipo'), name='uq_producto_relacionado_tipo')],
            },
        ),
    ]
