# Generated by Django 5.2.17 on 2026-08-12 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_default', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'lista de precios',
                'verbose_name_plural': 'listas de precios',
                'db_table': 'listas_precios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecioProducto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(default='COP', max_length=3)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('lista_precio', models.ForeignKey(db_column='lista_precio_id', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='precios.listaprecio')),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'precio de producto',
                'verbose_name_plural': 'precios de producto',
                'db_table': 'precios_producto',
                'indexes': [models.Index(fields=['producto', 'lista_precio'], name='idx_precio_prod_lista')],
            },
        ),
    ]
