# Generated by Django 5.2.17 on 2026-08-12 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, default='', max_length=150)),
                ('correo', models.EmailField(blank=True, db_index=True, max_length=150, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'clientes',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('VALOR_FIJO', 'Valor fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('min_compra', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usos_maximos', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'db_table': 'cupones',
            },
        ),
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_direccion', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.CharField(blank=True, default='', max_length=100)),
                ('barrio', models.CharField(blank=True, default='', max_length=100)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'dirección de cliente',
                'verbose_name_plural': 'direcciones de cliente',
                'db_table': 'direcciones_cliente',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=30, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('valor_domicilio', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('fecha_pedido', models.DateTimeField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='ventas.cliente')),
                ('sucursal', models.ForeignKey(db_column='sucursal_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='inventario.sucursal')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=16)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=16)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('producto', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.pedido')),
            ],
            options={
                'verbose_name': 'detalle de pedido',
                'verbose_name_plural': 'detalles de pedido',
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'fecha_pedido'], name='idx_pedido_cliente_fecha'),
        ),
    ]
